
POST http://ip-10-69-125-176.eu-west-1.compute.internal/service/api/person/changepassword/circabc_admin
content-type: application/json
Authorization: Basic admin:admin

{
    "newpw": "password"
}

###
POST  http://ip-10-69-125-176.eu-west-1.compute.internal/service/api/people
content-type: application/json
Authorization: Basic admin:admin

{
    "userName": "cat_admin",
    "firstName": "cat",
    "lastName": "admin",
    "email": "cat.admin@circabc.eu"
}

###
POST http://localhost/service/api/people
content-type: application/json
Authorization: Basic admin:admin

{
    "userName": "ig_admin",
    "firstName": "ig",
    "lastName": "admin",
    "email": "ig.admin@circabc.eu"
}

###
POST http://localhost/service/api/people
content-type: application/json
Authorization: Basic admin:admin

{
    "userName": "ig_author",
    "firstName": "ig",
    "lastName": "author",
    "email": "ig.author@circabc.eu"
}
###
POST http://localhost/service/api/people
content-type: application/json
Authorization: Basic admin:admin

{
    "userName": "ig_access",
    "firstName": "ig",
    "lastName": "access",
    "email": "ig.access@circabc.eu"
}

###
DELETE http://localhost/service/api/people/{userid}
content-type: application/json
Authorization: Basic admin:admin
